# Generated by Django 6.0.2 on 2026-03-01 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.movie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.seat'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
